version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ap-south-1 | docker login --username AWS --password-stdin $313006342006.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$ap-south-1.amazonaws.com/$idea
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $idea:$IMAGE_TAG .
      - docker tag $idea:$IMAGE_TAG $313006342006.dkr.ecr.$ap-south-1.amazonaws.com/$idea:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $313006342006.dkr.ecr.$ap-south-1.amazonaws.com/$idea:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
